
startup_shortcut_name: BumoAutostart.lnk
gcode_dirs: [ "./GCode_dir_bumo1", "./GCode_dir_bumo2" ]
target_dir: ./target_dir
suc_synonyms: [ gracefully, successfully, heavenly, victoriously, swimmingly, triumphantly, strongly, "quite well", splendidly ]
