# yamllint disable rule:line-length
# yamllint disable rule:indentation
# yamllint disable rule:comments-indentation
# too many spelling things, spell-checker: disable
---
- module-name: 'Bumo-GCode'
  dirs:
    - 'data'
  include-data-files:
    - source: 'icon/icon.ico'
      dest: 'icon/icon.ico'
  windows-info:
    console: disable
    icon: 'icon/icon.ico'
    company-name: "Koeger"
    product-name: "Bumo-GCode"
    file-version: "x.x.x"
    product-version: "x.x.x"
    file-description: "Copyier"
    copyright: "2026"
